spring:
  port: ${PORT:8080}
  connection-timeout: 300000
  tomcat:
    connection-timeout: 300000
  application:
    name: service-bookwallet

  datasource:
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  flyway:
    enabled: true
    locations: classpath:db-migration